import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { lightTheme } from '@/styles'

import { Button, ThemeProvider } from '@/components/ui'

import '@/styles/globals.css'

import { Sidebar } from '@/components'
import { cn } from '@/lib/utils'

const font = Poppins({
	subsets: ['latin'],
	display: 'swap',
	weight: ['400', '500', '600', '700'],
	variable: '--font-poppins',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html className={font.variable} lang='en' suppressHydrationWarning>
			<body className={cn('min-h-screen bg-background font-sans antialiased')}>
				<ThemeProvider
					value={{
						theme: lightTheme,
					}}
				>
					<div className='flex bg-primary'>
						<Sidebar />
						<div className=' w-[100vw] bg-primary pr-10'>{children}</div>
					</div>
				</ThemeProvider>
			</body>
		</html>
	)
}
