import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Topbar } from '@/components'

import '@/styles/globals.css'

import { ThemeProvider } from '@/components'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					inter.className,
				)}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<Topbar />
					{children}
				</ThemeProvider>
			</body>
		</html>
	)
}
